sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - stable
  
cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install codecov
script:
  - npm test
after_script:
  - codecov --token=$CODECOV_TOKEN
