sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - stable

cache:
  bundle: true
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

before_script:
  - npm install codecov
script:
  - npm test & npm run test:cy:ci $CYPRESS_RECORD_KEY
after_script:
  - codecov --token=$CODECOV_TOKEN
