sudo: false
language: node_js
node_js:
  - stable

cache:
  bundle: true
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

jobs:
  include:
    - allow_failures:
      - stage: Document deploy
        script: picidae build -f
        deploy:
          provider: pages
          skip_cleanup: true
          github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
          local_dir: public

    - stage: Unit testing
      before_script: npm install codecov
      script: npm test
      after_script: codecov --token=$CODECOV_TOKEN

    - stage: E2E testing
      script: npm run test:cy:ci $CYPRESS_RECORD_KEY



        # repo: $GH_REF
      # addons:
      #   sauce_connect:
      #     username: imcuttle
      #     access_key: ${SAUCE_ACCESS}
