sudo: false
language: node_js
node_js:
  - stable

cache:
  bundle: true
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

before_script:
  - npm install codecov
script:
  - npm test
  - npm run test:cy:ci $CYPRESS_RECORD_KEY
after_script:
  - codecov --token=$CODECOV_TOKEN

before_deploy:
  - picidae build -f
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  local_dir: public
  # repo: $GH_REF

# addons:
#   sauce_connect:
#     username: imcuttle
#     access_key: ${SAUCE_ACCESS}
